### ISSUE TITLE
The arrow keys don't move through the suggestion list on Google Chrome

### ISSUE THREAD

**Issue by tsleyson** [BartVanBeurden/ractive-autocomplete#2]
I'm using Google Chrome  51.0.2704.103 (64-bit) on Mac OS X Yosemite. This bug does not exist on Firefox 41.0.2 for Mac OS X Yosemite.

When I click in the input and start typing, a suggestion list appears. I should be able to navigate the list using the up and down arrow keys, and on Firefox I can. On Chrome, however, pressing the arrow keys has no effect at all. 

I believe the problem is that the template uses the `keypress` event (`on-keypress="keydown"`) instead of the `keydown` event (`on-keydown="keydown"), as `keypress` does not work correctly for escape or arrow keys on Chrome (see http://stackoverflow.com/q/3901063/3376926).

**Comment by BartVanBeurden** [comment]
Should be fixed.
